# Generated by Django 6.0.3 on 2026-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("savings", "Savings"), ("current", "Current")],
                default="savings",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "Naira"), ("USD", "Dollar"), ("EUR", "Euro")],
                default="NGN",
                max_length=10,
            ),
        ),
    ]
