# Generated by Django 6.0.3 on 2026-03-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
