# Generated by Django 6.0.3 on 2026-04-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_bank_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="face_verified",
            field=models.BooleanField(default=False),
        ),
    ]
