# Generated by Django 6.0.3 on 2026-04-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_face_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="employees.department",
            ),
        ),
    ]
