# Generated by Django 6.0.3 on 2026-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="is_single_role",
            field=models.BooleanField(default=False),
        ),
    ]
