# Generated by Django 6.0.4 on 2026-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="HR Suit", max_length=255)),
                ("timezone", models.CharField(default="Africa/Lagos", max_length=50)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                ("work_hours_per_day", models.PositiveIntegerField(default=8)),
                ("allow_late_arrival", models.BooleanField(default=True)),
                ("late_arrival_grace_minutes", models.PositiveIntegerField(default=15)),
                ("require_face_verification", models.BooleanField(default=True)),
                ("geo_fencing_enabled", models.BooleanField(default=False)),
                ("work_latitude", models.FloatField(blank=True, null=True)),
                ("work_longitude", models.FloatField(blank=True, null=True)),
                ("work_radius_meters", models.PositiveIntegerField(default=100)),
                ("payroll_day", models.PositiveIntegerField(default=25)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
                ),
                ("allow_manual_payslip", models.BooleanField(default=True)),
                ("carry_forward_leave", models.BooleanField(default=True)),
                ("max_carry_forward_days", models.PositiveIntegerField(default=10)),
                ("leave_approval_required", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("slack_notifications", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
    ]
