# Generated by Django 6.0.3 on 2026-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("company_admin", "Company Admin"),
                    ("hr", "HR"),
                    ("employee", "Employee"),
                ],
                default="company_admin",
                max_length=20,
            ),
        ),
    ]
