# Generated by Django 6.0.3 on 2026-03-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("hr", "HR"), ("employee", "Employee")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
