# Generated by Django 6.0.3 on 2026-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="09096598340", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("company_admin", "Company Admin"),
                    ("hr", "HR"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
