# Generated by Django 6.0.3 on 2026-03-24 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("employees", "0001_initial"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycomponent",
            name="company",
        ),
        migrations.RemoveField(
            model_name="salaryrecord",
            name="employee",
        ),
        migrations.RenameField(
            model_name="payslip",
            old_name="base_salary",
            new_name="basic_salary",
        ),
        migrations.AlterUniqueTogether(
            name="payrollrun",
            unique_together={("company", "month", "year")},
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="gross_salary",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="payroll_run",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="total_deductions",
        ),
        migrations.RemoveField(
            model_name="payslipitem",
            name="type",
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processed", "Processed"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="payroll",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="payroll.payrollrun",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="total_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="total_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslipitem",
            name="component_type",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="payslipitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payslipitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="payslipitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="PositionSalary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_salaries",
                        to="companies.company",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("allowance", "Allowance"),
                            ("deduction", "Deduction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_percentage", models.BooleanField(default=False)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_components",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionSalaryComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position_salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="payroll.positionsalary",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EmployeePayComponent",
        ),
        migrations.DeleteModel(
            name="PayComponent",
        ),
        migrations.DeleteModel(
            name="SalaryRecord",
        ),
        migrations.RemoveField(
            model_name="payrollrun",
            name="is_finalized",
        ),
    ]
