# Generated by Django 6.0.3 on 2026-03-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_bank_account_name_and_more"),
        ("payroll", "0002_remove_paycomponent_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionsalary",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary",
                to="employees.position",
            ),
        ),
    ]
