# Generated by Django 6.0.3 on 2026-04-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_alter_positionsalary_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salarycomponent",
            name="value",
        ),
        migrations.AddField(
            model_name="positionsalarycomponent",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
