# Generated by Django 6.0.3 on 2026-03-31 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_holiday"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
            ),
        ),
    ]
