# Generated by Django 6.0.3 on 2026-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_holiday_is_global_alter_holiday_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="is_recurring",
            field=models.BooleanField(default=True),
        ),
    ]
